apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
spec:  
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web  
        owner: boska
        release: dev
    spec:
      containers:
        - name: app
          image: nginx:1.27-perl
          ports:
            - containerPort: 80
