apiVersion: v1
kind: Pod
metadata:
  name: app

  labels:
    owner: mohamed
    app: app
    image: nginx
    release: dev
    environment: dev
spec:
  containers:
  - name: app
    image: nginx:latest
    ports:
      - containerPort: 80
