apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mm-deploy
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: mm-app
          image: nginx 
          ports:  
            - containerPort: 8080